name: test-github-actions
on: []
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - run: echo "test" > test.txt
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
