name: update-people-info
on: ["workflow_dispatch"]
jobs:
  update-people-data:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: "Install requests library"
        run: pip install requests
      - name: "Run staff data fetching script"
        run: python _fetch_staff_data.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
