name: update-people-info
on:
  schedule:
    - cron: 40 0 1 * *
jobs:
  update-people-data:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: "Install requests library"
        run: pip install requests
      - name: "Run staff data fetching script"
        run: python _fetch_staff_data.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
  keepalive-job:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
